import { supabase } from './supabase'

/**
 * Advisor invite library.
 *
 * Owners create invite links in Settings. Advisors follow the link, log in
 * (or sign up), and accept the invite — which creates a company_members row
 * that gives them read-only access to the owner's workspace.
 *
 * The invite token is a 32-byte hex string generated by Postgres. The full
 * invite URL is: https://[app]/invite/[token]
 */

// ---------------------------------------------------------------------------
// Owner-side — creating and managing invites
// ---------------------------------------------------------------------------

/**
 * Create a new invite for the current company.
 * Returns the created invite row (including the token).
 */
export async function createInvite({ companyId, userId, email = '' }) {
  const { data, error } = await supabase
    .from('company_invites')
    .insert({
      company_id: companyId,
      invited_by: userId,
      email:      email.trim() || null,
    })
    .select('*')
    .single()

  if (error) throw new Error(error.message)
  return data
}

/**
 * List all invites for a company (pending + accepted + revoked).
 */
export async function listInvites(companyId) {
  const { data, error } = await supabase
    .from('company_invites')
    .select('*')
    .eq('company_id', companyId)
    .order('created_at', { ascending: false })

  if (error) throw new Error(error.message)
  return data ?? []
}

/**
 * Revoke an invite so it can no longer be accepted.
 */
export async function revokeInvite(inviteId) {
  const { error } = await supabase
    .from('company_invites')
    .update({ status: 'revoked' })
    .eq('id', inviteId)

  if (error) throw new Error(error.message)
}

/**
 * List all advisors currently linked to a company.
 */
export async function listAdvisors(companyId) {
  const { data, error } = await supabase
    .from('company_members')
    .select('id, user_id, role, created_at')
    .eq('company_id', companyId)
    .order('created_at', { ascending: true })

  if (error) throw new Error(error.message)
  return data ?? []
}

/**
 * Remove an advisor's access to a company.
 */
export async function removeAdvisor(memberId) {
  const { error } = await supabase
    .from('company_members')
    .delete()
    .eq('id', memberId)

  if (error) throw new Error(error.message)
}

// ---------------------------------------------------------------------------
// Advisor-side — looking up and accepting invites
// ---------------------------------------------------------------------------

/**
 * Fetch an invite by its token.
 * Returns null if the token doesn't exist.
 */
export async function getInviteByToken(token) {
  const { data, error } = await supabase
    .from('company_invites')
    .select('id, company_id, email, role, status, expires_at, created_at')
    .eq('token', token)
    .maybeSingle()

  if (error) throw new Error(error.message)
  return data ?? null
}

/**
 * Accept an invite via the SECURITY DEFINER RPC.
 * Returns the company_id the advisor now has access to.
 */
export async function acceptInvite(token) {
  const { data, error } = await supabase
    .rpc('accept_invite', { p_token: token })

  if (error) throw new Error(error.message)
  return data // company_id (uuid)
}

/**
 * Fetch all companies the current user has advisor access to.
 * Returns an array of { member_id, company_id, company_name, role, created_at }.
 */
export async function getAdvisorMemberships(userId) {
  // company_members → join to companies for the name
  const { data, error } = await supabase
    .from('company_members')
    .select('id, company_id, role, created_at, companies(id, name)')
    .eq('user_id', userId)
    .order('created_at', { ascending: true })

  if (error) throw new Error(error.message)

  return (data ?? []).map(row => ({
    member_id:    row.id,
    company_id:   row.company_id,
    company_name: row.companies?.name ?? 'Unknown company',
    role:         row.role,
    created_at:   row.created_at,
  }))
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Build the shareable invite URL from a token.
 * Uses the current window.location.origin so it works in any environment.
 */
export function buildInviteUrl(token) {
  const base = typeof window !== 'undefined'
    ? window.location.origin
    : 'https://app.growthos.com'
  return `${base}/invite/${token}`
}
