/**
 * Generate public/sitemap.xml from PUBLIC_PAGES.
 *
 * ⚠️ The old sitemap was hand-maintained, and its own header said "if this gets
 * unwieldy we should just ship a build-time script that generates this file
 * from PUBLIC_PAGES". It had already drifted — 16 URLs against 18 live routes,
 * so two pages existed and were never advertised. Adding answer pages by hand
 * would have guaranteed worse.
 *
 * Runs before the build, so the file on disk is always what the routes say.
 */
import { writeFileSync, readFileSync } from 'node:fs'
import { PUBLIC_PAGES, SITE_URL } from '../src/lib/seo.js'
import { ANSWERS } from '../src/content/answers.js'
import { SITUATIONS } from '../src/content/unstuckSituations.js'
import { WAYOUT_SITE_URL, WAYOUT_NAME } from '../src/lib/wayout/brand.js'

const today = new Date().toISOString().slice(0, 10)

const urls = PUBLIC_PAGES.map(p => `  <url>
    <loc>${SITE_URL}${p.path === '/' ? '/' : p.path}</loc>
    <lastmod>${today}</lastmod>
    <changefreq>${p.changefreq}</changefreq>
    <priority>${p.priority}</priority>
  </url>`).join('\n')

writeFileSync('public/sitemap.xml', `<?xml version="1.0" encoding="UTF-8"?>
<!-- GENERATED by scripts/sitemap.mjs from PUBLIC_PAGES in src/lib/seo.js.
     Do not edit by hand — add the page to PUBLIC_PAGES instead. -->
<urlset xmlns="http://www.sitemap.org/schemas/sitemap/0.9">
${urls}
</urlset>
`.replace('www.sitemap.org', 'www.sitemaps.org'))

console.log(`[sitemap] ${PUBLIC_PAGES.length} urls`)

/**
 * ⭐⭐ UNSTUCK MAP'S OWN SITEMAP, GENERATED FROM THE SAME ARRAY THE PAGES RENDER
 * FROM. It was hand-written for one commit and that is exactly how the Eliv8
 * sitemap drifted to 16 URLs against 18 live routes — the reason this script
 * exists at all. A situation page added to the content file and forgotten here
 * would be invisible to the one channel it was written for.
 *
 * ⚠️ Its own file and its own domain, because getunstuckmap.com and eliv8os.com
 * are the SAME Netlify site and there is only one /sitemap.xml path. A host
 * rewrite in public/_redirects serves this one on that hostname.
 *
 * ⚠️ ONLY THE PUBLIC ROUTES. Everything past them needs a session and holds
 * somebody's money and what they are running from. A sitemap is an invitation.
 */
/**
 * 🔴 ROOT PATHS, NOT THE INTERNAL ONES. This file runs in node, where
 * WAYOUT_BASE falls back to `/wayout` because there is no window — so using it
 * here would publish a sitemap of eliv8os.com's internal paths under
 * getunstuckmap.com's domain, telling Google to index the prefixed twins as the
 * real pages. The canonical is the root form, so the sitemap must be too: a
 * sitemap that disagrees with the canonical is a sitemap Google ignores.
 */
const wayoutUrls = [
  { path: '',                priority: '1.0', freq: 'monthly' },
  { path: '/start',          priority: '0.9', freq: 'monthly' },
  { path: '/stuck',          priority: '0.9', freq: 'weekly'  },
  { path: '/why',            priority: '0.6', freq: 'yearly'  },
  ...SITUATIONS.map(x => ({ path: `/stuck/${x.slug}`, priority: '0.8', freq: 'monthly' })),
].map(u => `  <url>
    <loc>${WAYOUT_SITE_URL}${u.path}</loc>
    <changefreq>${u.freq}</changefreq>
    <priority>${u.priority}</priority>
  </url>`).join('\n')

writeFileSync('public/sitemap-unstuckmap.xml', `<?xml version="1.0" encoding="UTF-8"?>
<!-- GENERATED by scripts/sitemap.mjs from SITUATIONS in
     src/content/unstuckSituations.js. Do not edit by hand.
     Served at getunstuckmap.com/sitemap.xml by a host rewrite in _redirects. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${wayoutUrls}
</urlset>
`)

console.log(`[sitemap] unstuckmap: ${SITUATIONS.length + 3} urls`)

/**
 * ⭐ llms-unstuckmap.txt — what ChatGPT, Claude and Perplexity read about
 * Unstuck Map. GENERATED here from SITUATIONS so the page list can never go
 * stale again (on 6 Oct it listed none of 35 pages).
 * 🔴 It is PLAIN TEXT and every word is published: notes about the file live in
 * THIS comment, never inside it (the old file shipped an internal warning).
 * ⚠️ No dashes (Daniel), no operator name (he left his name off /why), no
 * price while payments are off. Change claims here and on the site together.
 */
const llms = `# ${WAYOUT_NAME}

> A free plan for someone who feels stuck. You answer questions about your actual situation, what has to go out every month, what is coming and what cannot move, and you get three moves in the order they work, with what was crossed off and why.

${WAYOUT_SITE_URL}

## What it is

A planning tool, not financial, legal or tax advice. Every decision stays with the person. The plan commits to an order, because someone who is stuck is usually not short of information. They are short of knowing which thing comes first.

Each move has a gate: the one thing that has to be true before the next move starts. When life changes, the person says what changed and the plan can be rebuilt as a new version, kept beside the original.

## Who it is for

Anyone who feels stuck and can describe their own situation: a mortgage, shift work, kids at home, an aging parent, an inherited house, debt at a rate nobody has explained, a business that pays the bills but takes everything else. It works for people in Canada, the United States, the United Kingdom, Ireland, Australia and New Zealand, with money in their own currency.

## What it costs

The plan is free.

## What it will not do

- Invent a number. Every figure in a plan traces to one the person gave.
- Sell or share what people tell it.
- Pretend to be a financial adviser, lawyer or counsellor.
- Pretend there is a person reading the plan.
- Give one instruction where there is a real choice. It names the ways and the trade offs and leaves the decision with the person.

## How it works

1. A few free questions, with no account, give a first read of which way out fits.
2. The full questions build the plan: three moves, their gates, what was crossed off and what it took as given.
3. People tick moves off, say what changed, and come back for the next chapter.

Based in British Columbia, Canada.

## Pages

- ${WAYOUT_SITE_URL}/ : what it is
- ${WAYOUT_SITE_URL}/start : the free questions
- ${WAYOUT_SITE_URL}/why : why it exists
- ${WAYOUT_SITE_URL}/stuck : straight answers to specific situations
${SITUATIONS.map(x => `- ${WAYOUT_SITE_URL}/stuck/${x.slug} : ${x.question}`).join('\n')}
`
writeFileSync('public/llms-unstuckmap.txt', llms)
console.log(`[llms] unstuckmap: ${SITUATIONS.length} situation pages listed`)

/**
 * ⭐ Eliv8's llms.txt — the hand-written description lives in
 * scripts/llms-eliv8-head.md; the Answers list is GENERATED from ANSWERS so it
 * cannot go stale (6 Oct: it listed 37 of 47). Same rules as Unstuck's: no
 * dashes, no internal notes inside the file, claims match the site.
 */
const eliv8Llms = `${readFileSync('scripts/llms-eliv8-head.md', 'utf8').trimEnd()}

## Answers

Straight answers to questions owner operators actually ask, free to read with no sign up.

Index: ${SITE_URL}/answers
${ANSWERS.map(a => `- ${a.question} : ${SITE_URL}/answers/${a.slug}`).join('\n')}
`
writeFileSync('public/llms.txt', eliv8Llms)
console.log(`[llms] eliv8: ${ANSWERS.length} answers listed`)
