/**
 * Generate public/sitemap.xml from PUBLIC_PAGES.
 *
 * ⚠️ The old sitemap was hand-maintained, and its own header said "if this gets
 * unwieldy we should just ship a build-time script that generates this file
 * from PUBLIC_PAGES". It had already drifted — 16 URLs against 18 live routes,
 * so two pages existed and were never advertised. Adding answer pages by hand
 * would have guaranteed worse.
 *
 * Runs before the build, so the file on disk is always what the routes say.
 */
import { writeFileSync } from 'node:fs'
import { PUBLIC_PAGES, SITE_URL } from '../src/lib/seo.js'
import { SITUATIONS } from '../src/content/unstuckSituations.js'
import { WAYOUT_SITE_URL } from '../src/lib/wayout/brand.js'

const today = new Date().toISOString().slice(0, 10)

const urls = PUBLIC_PAGES.map(p => `  <url>
    <loc>${SITE_URL}${p.path === '/' ? '/' : p.path}</loc>
    <lastmod>${today}</lastmod>
    <changefreq>${p.changefreq}</changefreq>
    <priority>${p.priority}</priority>
  </url>`).join('\n')

writeFileSync('public/sitemap.xml', `<?xml version="1.0" encoding="UTF-8"?>
<!-- GENERATED by scripts/sitemap.mjs from PUBLIC_PAGES in src/lib/seo.js.
     Do not edit by hand — add the page to PUBLIC_PAGES instead. -->
<urlset xmlns="http://www.sitemap.org/schemas/sitemap/0.9">
${urls}
</urlset>
`.replace('www.sitemap.org', 'www.sitemaps.org'))

console.log(`[sitemap] ${PUBLIC_PAGES.length} urls`)

/**
 * ⭐⭐ UNSTUCK MAP'S OWN SITEMAP, GENERATED FROM THE SAME ARRAY THE PAGES RENDER
 * FROM. It was hand-written for one commit and that is exactly how the Eliv8
 * sitemap drifted to 16 URLs against 18 live routes — the reason this script
 * exists at all. A situation page added to the content file and forgotten here
 * would be invisible to the one channel it was written for.
 *
 * ⚠️ Its own file and its own domain, because getunstuckmap.com and eliv8os.com
 * are the SAME Netlify site and there is only one /sitemap.xml path. A host
 * rewrite in public/_redirects serves this one on that hostname.
 *
 * ⚠️ ONLY THE PUBLIC ROUTES. Everything past them needs a session and holds
 * somebody's money and what they are running from. A sitemap is an invitation.
 */
/**
 * 🔴 ROOT PATHS, NOT THE INTERNAL ONES. This file runs in node, where
 * WAYOUT_BASE falls back to `/wayout` because there is no window — so using it
 * here would publish a sitemap of eliv8os.com's internal paths under
 * getunstuckmap.com's domain, telling Google to index the prefixed twins as the
 * real pages. The canonical is the root form, so the sitemap must be too: a
 * sitemap that disagrees with the canonical is a sitemap Google ignores.
 */
const wayoutUrls = [
  { path: '',                priority: '1.0', freq: 'monthly' },
  { path: '/start',          priority: '0.9', freq: 'monthly' },
  { path: '/stuck',          priority: '0.9', freq: 'weekly'  },
  { path: '/why',            priority: '0.6', freq: 'yearly'  },
  ...SITUATIONS.map(x => ({ path: `/stuck/${x.slug}`, priority: '0.8', freq: 'monthly' })),
].map(u => `  <url>
    <loc>${WAYOUT_SITE_URL}${u.path}</loc>
    <changefreq>${u.freq}</changefreq>
    <priority>${u.priority}</priority>
  </url>`).join('\n')

writeFileSync('public/sitemap-unstuckmap.xml', `<?xml version="1.0" encoding="UTF-8"?>
<!-- GENERATED by scripts/sitemap.mjs from SITUATIONS in
     src/content/unstuckSituations.js. Do not edit by hand.
     Served at getunstuckmap.com/sitemap.xml by a host rewrite in _redirects. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${wayoutUrls}
</urlset>
`)

console.log(`[sitemap] unstuckmap: ${SITUATIONS.length + 3} urls`)
