/**
 * Generate public/sitemap.xml from PUBLIC_PAGES.
 *
 * ⚠️ The old sitemap was hand-maintained, and its own header said "if this gets
 * unwieldy we should just ship a build-time script that generates this file
 * from PUBLIC_PAGES". It had already drifted — 16 URLs against 18 live routes,
 * so two pages existed and were never advertised. Adding answer pages by hand
 * would have guaranteed worse.
 *
 * Runs before the build, so the file on disk is always what the routes say.
 */
import { writeFileSync } from 'node:fs'
import { PUBLIC_PAGES, SITE_URL } from '../src/lib/seo.js'

const today = new Date().toISOString().slice(0, 10)

const urls = PUBLIC_PAGES.map(p => `  <url>
    <loc>${SITE_URL}${p.path === '/' ? '/' : p.path}</loc>
    <lastmod>${today}</lastmod>
    <changefreq>${p.changefreq}</changefreq>
    <priority>${p.priority}</priority>
  </url>`).join('\n')

writeFileSync('public/sitemap.xml', `<?xml version="1.0" encoding="UTF-8"?>
<!-- GENERATED by scripts/sitemap.mjs from PUBLIC_PAGES in src/lib/seo.js.
     Do not edit by hand — add the page to PUBLIC_PAGES instead. -->
<urlset xmlns="http://www.sitemap.org/schemas/sitemap/0.9">
${urls}
</urlset>
`.replace('www.sitemap.org', 'www.sitemaps.org'))

console.log(`[sitemap] ${PUBLIC_PAGES.length} urls`)
